#include "FileRuntime.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// ─────────────────────────────────────────────────────────────────────────────
// These functions are called from LLVM IR generated by CodeGen.
// They use plain C so no name mangling occurs.
// ─────────────────────────────────────────────────────────────────────────────

extern "C" {

// ── nexa_file_read(path) → char* ─────────────────────────────────────────────
// Reads the entire file at `path` into a heap-allocated null-terminated string.
// Returns nullptr on failure (CodeGen checks and prints an error).
// The caller (compiled Nexa program) does NOT free this — it lives for the
// lifetime of the program. For short-lived scripts this is acceptable;
// for long-running programs add a nexa_file_free() call.
char* nexa_file_read(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "[nexa runtime] error: cannot open '%s' for reading\n", path);
        return nullptr;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    rewind(f);

    char* buf = (char*)malloc(size + 1);
    if (!buf) {
        fclose(f);
        fprintf(stderr, "[nexa runtime] error: out of memory reading '%s'\n", path);
        return nullptr;
    }

    size_t read = fread(buf, 1, size, f);
    buf[read] = '\0';
    fclose(f);
    return buf;
}

// ── nexa_file_write(path, content) → void ────────────────────────────────────
// Overwrites (or creates) the file at `path` with `content`.
void nexa_file_write(const char* path, const char* content) {
    FILE* f = fopen(path, "w");
    if (!f) {
        fprintf(stderr, "[nexa runtime] error: cannot open '%s' for writing\n", path);
        return;
    }
    fputs(content, f);
    fclose(f);
}

// ── nexa_file_append(path, content) → void ───────────────────────────────────
// Appends `content` to the file at `path` (creates it if it doesn't exist).
void nexa_file_append(const char* path, const char* content) {
    FILE* f = fopen(path, "a");
    if (!f) {
        fprintf(stderr, "[nexa runtime] error: cannot open '%s' for appending\n", path);
        return;
    }
    fputs(content, f);
    fclose(f);
}

// ── nexa_file_exists(path) → int ─────────────────────────────────────────────
// Returns 1 if file exists and is readable, 0 otherwise.
int nexa_file_exists(const char* path) {
    FILE* f = fopen(path, "r");
    if (!f) return 0;
    fclose(f);
    return 1;
}

} // extern "C"